import seed from "./catalog-seed.json" with { type: "json" }

export type IsoThumbMeta = {
  url: string
  wash: string
}

const WASHES: Record<string, string> = {
  "anonymous-mask": "oklch(0.91 0.048 85)",
  "ash-crop": "oklch(0.91 0.042 85)",
  "baggy-skull-pants": "oklch(0.91 0.032 245)",
  "bear-hat": "oklch(0.91 0.042 85)",
  "brown-shoes": "oklch(0.91 0.042 85)",
  "camo-pants": "oklch(0.91 0.055 130.2)",
  "christmas-sweater": "oklch(0.91 0.042 85)",
  "dark-sweatpants": "oklch(0.91 0.032 245)",
  "football-helmet": "oklch(0.91 0.042 85)",
  "heartbreaker-hair": "oklch(0.91 0.042 85)",
  "ink-fall": "oklch(0.91 0.042 85)",
  "knee-high-converse": "oklch(0.91 0.032 245)",
  "leather-jacket": "oklch(0.91 0.032 245)",
  "moon-pants": "oklch(0.91 0.032 245)",
  "ombre-hair": "oklch(0.91 0.028 250)",
  "open-plaid": "oklch(0.91 0.055 202.5)",
  "pink-hoodie": "oklch(0.91 0.055 350)",
  "rose-drape": "oklch(0.91 0.055 350)",
  "skull-mask": "oklch(0.91 0.028 250)",
  sneakers: "oklch(0.91 0.028 250)",
  "striped-coat": "oklch(0.91 0.055 300)",
  "winter-coat": "oklch(0.91 0.042 85)",
}

/**
 * Pieces with a pre-rendered 180×210 PNG in public/iso/pieces (generated by
 * scripts/export-isometric.html). Importing skin/iso.ts pulls in three.js +
 * skinview3d, so callers that only need the static thumb must stay decoupled.
 */
export const ISO_PIECE_THUMBS: ReadonlyMap<string, IsoThumbMeta> = new Map(
  seed
    .map((row) => row.id)
    .filter((id) => id in WASHES)
    .map((id) => [
      id,
      {
        url: `${import.meta.env.BASE_URL}iso/pieces/${id}.png`,
        wash: WASHES[id] ?? "",
      } satisfies IsoThumbMeta,
    ]),
)

export function isoPieceStaticThumb(id: string): IsoThumbMeta | null {
  return ISO_PIECE_THUMBS.get(id) ?? null
}
